// import { RouteInfo } from "./sidebar.metadata";
// export const ROUTES: RouteInfo[] = [
//   {
//     path: "",
//     title: "Please Select the Task",
//     moduleName: "task",
//     img: "home",
//     class: "menu-toggle",
//     submenu: [
//       {
//         path: "/task/extract-vulnerability",
//         title: "Extract Vulnerability11",
//         moduleName: "task",
//         img: "",
//         class: "ml-menu",
//         submenu: [],
//       },
//     ],
//   },
//   {
//     path: "",
//     title: "Please Select Assessment",
//     moduleName: "assessment",
//     img: "material-icons-two-tone",
//     class: "menu-toggle",
//     submenu: [
//       {
//         path: "/assessment/soc-2",
//         title: "SOC-2",
//         moduleName: "assessment",
//         img: "",
//         class: "ml-menu",
//         submenu: [],
//       },
//       {
//         path: "/assessment/cmmc",
//         title: "CMMC",
//         moduleName: "assessment",
//         img: "",
//         class: "ml-menu",
//         submenu: [],
//       },
//       {
//         path: "/assessment/iso",
//         title: "ISO 27001",
//         moduleName: "assessment",
//         img: "",
//         class: "ml-menu",
//         submenu: [],
//       },
//       {
//         path: "/assessment/nistsp5",
//         title: "NIST SP 800-53 Rev 5",
//         moduleName: "assessment",
//         img: "",
//         class: "ml-menu",
//         submenu: [],
//       },
//       {
//         path: "/assessment/nistsp4",
//         title: "NIST SP 800-53 Rev 4",
//         moduleName: "assessment",
//         img: "",
//         class: "ml-menu",
//         submenu: [],
//       },
//       // {
//       //   path: "/assessment/swift-cyber-security",
//       //   title: "Swift Cyber Security",
//       //   moduleName: "assessment",
//       //   img: "",
//       //   class: "ml-menu",
//       //   submenu: [],
//       // },
//       {
//         path: "/assessment/gdpr",
//         title: "GDPR",
//         moduleName: "assessment",
//         img: "",
//         class: "ml-menu",
//         submenu: [],
//       },
//     ],
//   },
// ];
